export const theme = {
  colors: {
    background: '#F5F6F7',
    surface: '#FFFFFF',
    surfaceMuted: '#F9FAFB',
    textPrimary: '#171717',
    textSecondary: '#5B5B5B',
    textInverse: '#FFFFFF',
    border: '#E4E5E7',
    borderStrong: '#D1D5DB',
    primary: '#17A34A',
    primaryPressed: '#13853C',
    secondary: '#2563EB',
    secondaryPressed: '#1D4ED8',
    outline: '#E5E7EB',
    danger: '#DC2626',
    success: '#16A34A',
    warning: '#EAB308',
    info: '#2563EB',
    disabled: '#E5E7EB',
    disabledText: '#9CA3AF',
    inputBackground: '#FFFFFF',
    inputPlaceholder: '#9CA3AF',
    infoTintBackground: '#EFF6FF',
    infoTintBorder: '#BFDBFE',
  },
  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  radius: {
    xs: 6,
    sm: 8,
    md: 12,
    lg: 16,
    pill: 999,
  },
  fontSizes: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 22,
    xxl: 28,
    display: 45,
  },
  fontWeights: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
  shadows: {
    none: {
      shadowColor: 'transparent',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffset: { width: 0, height: 0 },
      elevation: 0,
    },
    card: {
      shadowColor: '#000',
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
  },
  iconSizes: {
    xs: 12,
    sm: 16,
    md: 20,
    lg: 24,
    xl: 28,
  },
  components: {
    screenPaddingHorizontal: 16,
    buttonHeights: {
      sm: 36,
      md: 44,
      lg: 50,
      icon: 38,
    },
    inputHeight: 44,
    cardPadding: 16,
    maxContentWidth: 420,
  },
  recycle: {
    headerScore: '#0F766E',
    headerSubtitle: '#2563EB',
    iconNeutral: '#4B5563',
    iconButtonBg: '#E5E7EB',
    iconButtonSelectedBg: '#DCFCE7',
    iconButtonCameraBg: '#2563EB',
    tabActive: '#17A34A',
    tabInactive: '#171717',
  },
} as const;

export type AppTheme = typeof theme;

