-- Declarative schema source for Reciclame.
-- Edit files in this directory and generate additive migrations with:
--   supabase db diff -f <change_name>
-- Keep supabase/migrations as immutable applied history.
