// Shim — the actual file is auto-generated by scripts/gen-avatar-assets.js into
// src/features/profile/data/avatarAssets.ts. Update OUT in that script when convenient.
export { avatarAssets } from '@/src/features/profile/data/avatarAssets';
