export const routes = {
  home: '/(tabs)/map',
  profileAchievements: '/profile/achievements',
  profileFeaturedBadges: '/profile/featured-badges',
  profileAvatar: '/profile/avatar',
  profileSettings: '/profile/settings',
  profileStreak: '/profile/streak',
  recycleCamera: '/recycle/camera',
  recycleProcessing: '/recycle/processing',
  recycleManual: '/recycle/manual',
  recycleInstructions: '/recycle/instructions',
  recycleSuccess: '/recycle/success',
  recycleHistory: '/recycle/history',
  friendsAdd: '/(tabs)/friends/add',
  devPanel: '/dev',
} as const;
