#!/bin/bash

local_branch_name=$(git rev-parse --abbrev-ref HEAD)

valid_branch_regex="^(feature|fix|docs|refactor|test|chore)\/[a-z0-9-]+$"

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
  echo "---------------------------------------------------------------"
  echo "Nombre de rama invalido: '$local_branch_name'"
  echo "El formato obligatorio es: [tipo-de-rama]/[nombre-descriptivo]"
  echo "Tipos permitidos: feature/, fix/, docs/, refactor/, test/, chore/"
  echo "Ejemplo: feature/foo-functionality"
  echo "---------------------------------------------------------------"
  exit 1
fi

exit 0
